"""add elevation_gain_m to tp_completed_workouts

Revision ID: 093834b5c578
Revises: 8f4c72a19fb0
Create Date: 2026-04-05 18:30:26.156403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '093834b5c578'
down_revision: Union[str, Sequence[str], None] = '8f4c72a19fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tp_completed_workouts', sa.Column('elevation_gain_m', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tp_completed_workouts', 'elevation_gain_m')
    # ### end Alembic commands ###
