"""add alcohol_drinks to nutrition_daily

Revision ID: 30739edcf036
Revises: 66c6c6a77a8f
Create Date: 2026-04-04 21:04:47.106450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30739edcf036'
down_revision: Union[str, Sequence[str], None] = '66c6c6a77a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition_daily', sa.Column('alcohol_drinks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutrition_daily', 'alcohol_drinks')
    # ### end Alembic commands ###
