"""add calories_goal and protein_goal_g to nutrition_daily

Revision ID: 5da92dec52c1
Revises: b280055bd6db
Create Date: 2026-04-04 18:13:57.279387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5da92dec52c1'
down_revision: Union[str, Sequence[str], None] = 'b280055bd6db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition_daily', sa.Column('calories_goal', sa.Integer(), nullable=True))
    op.add_column('nutrition_daily', sa.Column('protein_goal_g', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutrition_daily', 'protein_goal_g')
    op.drop_column('nutrition_daily', 'calories_goal')
    # ### end Alembic commands ###
