"""add description to tp_completed_workouts

Revision ID: 66c6c6a77a8f
Revises: aeb2016ef3e1
Create Date: 2026-04-04 20:57:57.353977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c6c6a77a8f'
down_revision: Union[str, Sequence[str], None] = 'aeb2016ef3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tp_completed_workouts', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tp_completed_workouts', 'description')
    # ### end Alembic commands ###
