"""add workout_details_json to tp_completed_workouts

Revision ID: ac43394b8bd6
Revises: 093834b5c578
Create Date: 2026-04-05 23:00:09.792055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac43394b8bd6'
down_revision: Union[str, Sequence[str], None] = '093834b5c578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tp_completed_workouts', sa.Column('workout_details_json', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tp_completed_workouts', 'workout_details_json')
    # ### end Alembic commands ###
