"""add fitbit tokens to users

Revision ID: aeb2016ef3e1
Revises: 5da92dec52c1
Create Date: 2026-04-04 20:16:18.984916

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aeb2016ef3e1'
down_revision: str | Sequence[str] | None = '5da92dec52c1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fitbit_access_token', sa.Text(), nullable=False))
    op.add_column('users', sa.Column('fitbit_refresh_token', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fitbit_refresh_token')
    op.drop_column('users', 'fitbit_access_token')
    # ### end Alembic commands ###
