"""create all tables

Revision ID: ef892169eb33
Revises:
Create Date: 2026-03-07 19:46:48.648436

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef892169eb33"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("garmin_id", sa.String(length=50), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("type", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("duration_sec", sa.Integer(), nullable=True),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.Column("avg_hr", sa.Integer(), nullable=True),
        sa.Column("max_hr", sa.Integer(), nullable=True),
        sa.Column("avg_power", sa.Float(), nullable=True),
        sa.Column("max_power", sa.Float(), nullable=True),
        sa.Column("training_effect_aerobic", sa.Float(), nullable=True),
        sa.Column("training_effect_anaerobic", sa.Float(), nullable=True),
        sa.Column("vo2max_estimate", sa.Float(), nullable=True),
        sa.Column("elevation_gain", sa.Float(), nullable=True),
        sa.Column("tss", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("garmin_id"),
    )
    op.create_index(op.f("ix_activities_date"), "activities", ["date"], unique=False)
    op.create_table(
        "daily_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("steps", sa.Integer(), nullable=True),
        sa.Column("calories_total", sa.Integer(), nullable=True),
        sa.Column("calories_active", sa.Integer(), nullable=True),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column("floors", sa.Integer(), nullable=True),
        sa.Column("avg_hr", sa.Integer(), nullable=True),
        sa.Column("resting_hr", sa.Integer(), nullable=True),
        sa.Column("max_hr", sa.Integer(), nullable=True),
        sa.Column("min_hr", sa.Integer(), nullable=True),
        sa.Column("stress_avg", sa.Integer(), nullable=True),
        sa.Column("stress_max", sa.Integer(), nullable=True),
        sa.Column("body_battery_high", sa.Integer(), nullable=True),
        sa.Column("body_battery_low", sa.Integer(), nullable=True),
        sa.Column("spo2_avg", sa.Float(), nullable=True),
        sa.Column("respiration_avg", sa.Float(), nullable=True),
        sa.Column("hydration_ml", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
    )
    op.create_table(
        "nutrition_daily",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.Column("protein_g", sa.Float(), nullable=True),
        sa.Column("carbs_g", sa.Float(), nullable=True),
        sa.Column("fat_g", sa.Float(), nullable=True),
        sa.Column("fiber_g", sa.Float(), nullable=True),
        sa.Column("sodium_mg", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
    )
    op.create_table(
        "performance_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("tss", sa.Float(), nullable=True),
        sa.Column("atl", sa.Float(), nullable=True),
        sa.Column("ctl", sa.Float(), nullable=True),
        sa.Column("tsb", sa.Float(), nullable=True),
        sa.Column("training_load_7d", sa.Float(), nullable=True),
        sa.Column("training_load_28d", sa.Float(), nullable=True),
        sa.Column("recovery_score", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
    )
    op.create_table(
        "sleep_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("sleep_start", sa.DateTime(), nullable=True),
        sa.Column("sleep_end", sa.DateTime(), nullable=True),
        sa.Column("total_sleep_min", sa.Integer(), nullable=True),
        sa.Column("deep_min", sa.Integer(), nullable=True),
        sa.Column("light_min", sa.Integer(), nullable=True),
        sa.Column("rem_min", sa.Integer(), nullable=True),
        sa.Column("awake_min", sa.Integer(), nullable=True),
        sa.Column("avg_hr_sleep", sa.Integer(), nullable=True),
        sa.Column("avg_hrv", sa.Float(), nullable=True),
        sa.Column("avg_spo2_sleep", sa.Float(), nullable=True),
        sa.Column("sleep_score", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("date"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("garmin_email", sa.String(length=255), nullable=False),
        sa.Column("garmin_password", sa.String(length=512), nullable=False),
        sa.Column("mfp_username", sa.String(length=255), nullable=False),
        sa.Column("mfp_password", sa.String(length=512), nullable=False),
        sa.Column("hr_max", sa.Integer(), nullable=False),
        sa.Column("hr_rest", sa.Integer(), nullable=False),
        sa.Column("hr_threshold", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "strength_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("exercise_name", sa.String(length=255), nullable=False),
        sa.Column("sets", sa.Integer(), nullable=True),
        sa.Column("reps", sa.Integer(), nullable=True),
        sa.Column("weight_kg", sa.Float(), nullable=True),
        sa.Column("tonnage", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("strength_sessions")
    op.drop_table("users")
    op.drop_table("sleep_sessions")
    op.drop_table("performance_metrics")
    op.drop_table("nutrition_daily")
    op.drop_table("daily_summaries")
    op.drop_index(op.f("ix_activities_date"), table_name="activities")
    op.drop_table("activities")
    # ### end Alembic commands ###
